export const MENTOR_TOPIC_OPTIONS = [
  "DevOps",
  "Data",
  "Cloud / Infrastructure",
  "Backend Engineer",
  "AI / Machine Learning",
  "Product",
  "Mobile (iOS / Android)",
  "Full Stack",
  "Front End",
  "Embedded / Hardware",
  "Business Development (BizDev)",
  "Technical Writing",
  "Security / Cyber",
  "R&D / Research",
  "Partnerships",
  "Marketing",
  "Growth / Acquisition",
  "Business Operations (BizOps)",
  "Solutions Engineering / Pre-Sales",
  "Sales",
  "Revenue Operations (RevOps)",
  "Operations",
  "IT",
  "Design (UX/UI)",
  "BI / Business Intelligence",
  "Agile / Scrum Master",
  "Customer Care",
  "Community Management",
  "Technical Project Manager",
  "QA",
  "Finance",
  "HR",
  "Technical Support",
  "Customer Success",
  "אחר",
];
